# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/falcon/CodeProjs/vitapong

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/falcon/CodeProjs/vitapong

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/falcon/CodeProjs/vitapong/CMakeFiles /home/falcon/CodeProjs/vitapong//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/falcon/CodeProjs/vitapong/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vitapong

# Build rule for target.
vitapong: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vitapong
.PHONY : vitapong

# fast build rule for target.
vitapong/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vitapong.dir/build.make CMakeFiles/vitapong.dir/build
.PHONY : vitapong/fast

#=============================================================================
# Target rules for targets named vitapong-velf

# Build rule for target.
vitapong-velf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vitapong-velf
.PHONY : vitapong-velf

# fast build rule for target.
vitapong-velf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vitapong-velf.dir/build.make CMakeFiles/vitapong-velf.dir/build
.PHONY : vitapong-velf/fast

#=============================================================================
# Target rules for targets named vitapong.self-self

# Build rule for target.
vitapong.self-self: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vitapong.self-self
.PHONY : vitapong.self-self

# fast build rule for target.
vitapong.self-self/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vitapong.self-self.dir/build.make CMakeFiles/vitapong.self-self.dir/build
.PHONY : vitapong.self-self/fast

#=============================================================================
# Target rules for targets named vitapong.vpk-vpk

# Build rule for target.
vitapong.vpk-vpk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vitapong.vpk-vpk
.PHONY : vitapong.vpk-vpk

# fast build rule for target.
vitapong.vpk-vpk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vitapong.vpk-vpk.dir/build.make CMakeFiles/vitapong.vpk-vpk.dir/build
.PHONY : vitapong.vpk-vpk/fast

pong.obj: pong.c.obj
.PHONY : pong.obj

# target to build an object file
pong.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vitapong.dir/build.make CMakeFiles/vitapong.dir/pong.c.obj
.PHONY : pong.c.obj

pong.i: pong.c.i
.PHONY : pong.i

# target to preprocess a source file
pong.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vitapong.dir/build.make CMakeFiles/vitapong.dir/pong.c.i
.PHONY : pong.c.i

pong.s: pong.c.s
.PHONY : pong.s

# target to generate assembly for a file
pong.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vitapong.dir/build.make CMakeFiles/vitapong.dir/pong.c.s
.PHONY : pong.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vitapong-velf"
	@echo "... vitapong.self-self"
	@echo "... vitapong.vpk-vpk"
	@echo "... vitapong"
	@echo "... pong.obj"
	@echo "... pong.i"
	@echo "... pong.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

